# Generated by Django 6.0.5 on 2026-05-20 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Forfait'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite')], max_length=1)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('chantier', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('validite_jours', models.IntegerField(default=30)),
                ('taux_mo', models.DecimalField(decimal_places=2, default=46.0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('destinataire', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('sent', 'Envoyée'), ('paid', 'Payée')], default='draft', max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('bypass_validation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.devis')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('bypass', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.devis')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.facture')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('F', 'Forfait'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Financement')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('ouvert', models.BooleanField(default=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.devis')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='core.lignedevis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'ordering': ['ordre'],
            },
        ),
    ]
