# Generated by Django 6.0.5 on 2026-05-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='type_ligne',
            field=models.CharField(choices=[('F', 'Forfait'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Financement'), ('TITRE', 'Titre')], max_length=5),
        ),
    ]
