# Generated by Django 6.0.5 on 2026-05-21 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lignedevis_type_ligne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Équipe',
                'ordering': ['service', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametresAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Compagnons Bâtisseurs Bretagne', max_length=200)),
                ('siret', models.CharField(blank=True, max_length=50)),
                ('ape', models.CharField(blank=True, max_length=20)),
                ('forme_juridique', models.CharField(blank=True, default='Association loi 1901', max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('site_web', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('couleur_principale', models.CharField(default='#6B1F3A', help_text='Code hexadécimal ex: #6B1F3A', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#2BBFA4', help_text='Code hexadécimal ex: #2BBFA4', max_length=7)),
                ('couleur_accent', models.CharField(default='#E8A020', help_text='Code hexadécimal ex: #E8A020', max_length=7)),
                ('slogan', models.CharField(blank=True, default='La solidarité, un chantier à partager', max_length=200)),
            ],
            options={
                'verbose_name': 'Paramètres association',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('conditions_devis', models.TextField(blank=True, help_text='Conditions de vente affichées sur les devis de ce service')),
                ('conditions_facture', models.TextField(blank=True, help_text='Conditions de vente affichées sur les factures de ce service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['territoire', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Territoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Ex: 35, 29, COB', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Territoire',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Article'},
        ),
        migrations.RemoveField(
            model_name='devis',
            name='validite_jours',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='reference',
        ),
        migrations.AddField(
            model_name='article',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text='Null = article partagé, renseigné = bibliothèque personnelle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_perso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier_adresse1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier_adresse2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier_cp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='devis',
            name='chantier_ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devis',
            name='conditions_devis',
            field=models.TextField(blank=True, help_text='Conditions de vente pour ce devis (copié depuis les préférences à la création)'),
        ),
        migrations.AddField(
            model_name='devis',
            name='date_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='fin_group_title',
            field=models.CharField(default='Financements', help_text='Titre du groupe de financements', max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='conditions_facture',
            field=models.TextField(blank=True, help_text='Conditions de vente pour cette facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, help_text='Assigné automatiquement à la validation', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_doc',
            field=models.CharField(choices=[('facture', 'Facture'), ('avoir', 'Avoir')], default='facture', max_length=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.categorie'),
        ),
        migrations.AddField(
            model_name='devis',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='core.equipe'),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('F', 'Forfait'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Financement'), ('TITRE', 'Titre')], max_length=5)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('quantite_originale', models.DecimalField(decimal_places=3, default=1, help_text='Quantité du devis original, pour référence', max_digits=10)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('ouvert', models.BooleanField(default=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.facture')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='core.lignefacture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Responsable de service'), ('technicien', 'Technicien / Chargé de projet'), ('comptable', 'Comptable')], default='technicien', max_length=20)),
                ('taux_mo_defaut', models.DecimalField(decimal_places=2, default=46.0, help_text='Taux horaire MO par défaut pour les nouveaux devis', max_digits=6)),
                ('saisie_ht', models.BooleanField(default=False, help_text='Si activé, les prix matériaux sont saisis HT et convertis en TTC (+20%)')),
                ('categories_biblio', models.JSONField(blank=True, default=list, help_text='Ordre et visibilité des catégories dans la bibliothèque')),
                ('conditions_devis', models.TextField(blank=True, help_text='Conditions de vente personnelles pour les devis (prioritaire sur le service)')),
                ('conditions_facture', models.TextField(blank=True, help_text='Conditions de vente personnelles pour les factures')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='core.equipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='territoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.territoire'),
        ),
    ]
