# Generated by Django 6.0.5 on 2026-05-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorie_equipe_parametresassociation_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='equipe',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='equipes',
            field=models.ManyToManyField(blank=True, help_text='Équipes habituelles (filtre par défaut dans les listes)', related_name='membres', to='core.equipe'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='service',
            field=models.ForeignKey(blank=True, help_text="Service d'appartenance principal", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='core.service'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='conditions_devis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='conditions_facture',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='saisie_ht',
            field=models.BooleanField(default=False, help_text='Prix matériaux saisis HT, convertis en TTC (+20%)'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='taux_mo_defaut',
            field=models.DecimalField(decimal_places=2, default=46.0, max_digits=6),
        ),
    ]
