# Generated by Django 6.0.5 on 2026-05-23 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profilutilisateur_equipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='type_ligne',
            field=models.CharField(choices=[('F', 'Forfait'), ('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Financement'), ('TITRE', 'Titre')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='type_ligne',
            field=models.CharField(choices=[('F', 'Forfait'), ('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Financement'), ('TITRE', 'Titre')], max_length=5),
        ),
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lignes', models.JSONField(blank=True, default=list, help_text='Arbre JSON identique aux lignes de devis')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bibliotheque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bibliothèque',
            },
        ),
    ]
