# Generated by Django 6.0.5 on 2026-05-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lignedevis_type_ligne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Responsable hiérarchique direct (Responsable secteur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techniciens', to='core.devis'),
        ),
    ]
