# Generated by Django 6.0.5 on 2026-05-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devis_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='responsable',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Responsable hiérarchique direct (Responsable secteur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techniciens', to='core.profilutilisateur'),
        ),
    ]
