# Generated by Django 6.0.5 on 2026-05-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_devis_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='libelle',
            field=models.CharField(blank=True, help_text='Court libellé affiché dans le récapitulatif des factures précédentes', max_length=200),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='ligne_devis_source',
            field=models.ForeignKey(blank=True, help_text="Ligne du devis à l'origine de cette ligne de facture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_factures', to='core.lignedevis'),
        ),
    ]
