# Generated by Django 6.0.5 on 2026-05-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_facture_libelle_ligne_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_versement',
            field=models.DateField(blank=True, help_text="Date de versement de l'acompte (renseignée sur la facture normale)", null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_doc',
            field=models.CharField(choices=[('facture', 'Facture'), ('acompte', "Facture d'acompte"), ('appel', "Facture d'appel convention"), ('avoir', 'Avoir')], default='facture', max_length=10),
        ),
    ]
