# Generated by Django 6.0.5 on 2026-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facture_date_versement_alter_facture_type_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='coordonnees_cb',
            field=models.TextField(blank=True, help_text='Coordonnées CB du contact pour ce devis (copié depuis le profil à la création)'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='coordonnees_cb',
            field=models.TextField(blank=True, help_text='Coordonnées CB affichées sur les devis/factures (nom, fonction, tél.)'),
        ),
    ]
