# Generated by Django 6.0.5 on 2026-06-01 20:46

from django.db import migrations


def assign_clients(apps, schema_editor):
    """
    Attribue les clients existants (sans créateur) au 1er admin :
    profil role == 'admin', sinon 1er superuser. Si aucun, on laisse null.
    """
    Client = apps.get_model('core', 'Client')
    ProfilUtilisateur = apps.get_model('core', 'ProfilUtilisateur')
    User = apps.get_model('auth', 'User')

    admin_profil = (
        ProfilUtilisateur.objects.filter(role='admin')
        .order_by('pk').first()
    )
    if admin_profil:
        admin_user_id = admin_profil.user_id
    else:
        superuser = User.objects.filter(is_superuser=True).order_by('pk').first()
        admin_user_id = superuser.pk if superuser else None

    if admin_user_id is None:
        return

    Client.objects.filter(created_by__isnull=True).update(created_by_id=admin_user_id)


def reverse(apps, schema_editor):
    # Pas de retour arrière fiable : on ne touche pas aux données.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_code_postal_client_created_by_client_ville_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_clients, reverse),
    ]
