# Generated by Django 6.0.5 on 2026-06-01 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_assign_clients_to_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='zone_financement',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BibliothèqueAides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('type_ligne', models.CharField(choices=[('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('FIN', 'Financement')], default='FIN', max_length=5)),
                ('montant_defaut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unite', models.CharField(blank=True, default='forfait', max_length=50)),
                ('organisme', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aides_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aide / financement',
                'verbose_name_plural': 'Aides / financements',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='aide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations', to='core.bibliothèqueaides'),
        ),
    ]
