# Generated by Django 6.0.5 on 2026-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_set_zone_financement_for_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='invitation_envoyee',
            field=models.BooleanField(default=False, help_text="Email d'invitation envoyé avec succès"),
        ),
    ]
