# Generated by Django 6.0.5 on 2026-06-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profil_invitation_envoyee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('association', 'Association'), ('bailleur', 'Bailleur'), ('collectivite', 'Collectivité'), ('autre', 'Autre')], default='particulier', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_directes', to='core.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='coordonnees_cb',
            field=models.TextField(blank=True, help_text='Coordonnées CB (snapshot à la création depuis le profil) — utilisé pour les factures compta sans devis'),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='core.facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='devis',
            field=models.ForeignKey(blank=True, help_text='Optionnel : factures compta (structure/appel) créées sans devis', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.devis'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_doc',
            field=models.CharField(choices=[('facture', 'Facture'), ('acompte', "Facture d'acompte"), ('appel', "Facture d'appel convention"), ('structure', 'Facture structure'), ('avoir', 'Avoir')], default='facture', max_length=10),
        ),
        migrations.CreateModel(
            name='ContactClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, help_text='Service destinataire (ex. Direction du patrimoine)', max_length=200)),
                ('nom', models.CharField(blank=True, help_text='Interlocuteur / technicien', max_length=200)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client')),
            ],
            options={
                'verbose_name': 'Contact client',
                'ordering': ['service', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='contact_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.contactclient'),
        ),
    ]
