# Generated by Django 6.0.5 on 2026-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_type_client_facture_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='dashboard_config',
            field=models.JSONField(blank=True, default=dict, help_text='Disposition du tableau de bord (widgets, ordre, portée)'),
        ),
    ]
