# Generated by Django 6.0.5 on 2026-06-06 07:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profilutilisateur_dashboard_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo_cle', models.CharField(blank=True, help_text="Clé d'un logo statique embarqué (base64), comme le logo CB", max_length=100)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Financeur',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='activite',
            field=models.CharField(blank=True, choices=[('gros_oeuvre', 'Gros œuvre'), ('second_oeuvre', 'Second œuvre')], help_text='Filtre du suivi de production (gros / second œuvre)', max_length=20),
        ),
        migrations.AddField(
            model_name='equipe',
            name='encadrant',
            field=models.ForeignKey(blank=True, help_text="Chef d'équipe fixe (= ETI sur la fiche d'émargement)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_encadrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametresassociation',
            name='cout_jour_salarie',
            field=models.DecimalField(decimal_places=2, default=Decimal('82.50'), help_text="Coût d'un salarié·jour (pour la colonne coût réel du suivi de production)", max_digits=8),
        ),
        migrations.AddField(
            model_name='parametresassociation',
            name='taux_jour_facturable',
            field=models.DecimalField(decimal_places=2, default=Decimal('472.00'), help_text="Convertit le coût MO d'un devis en jours facturables (coût MO / taux)", max_digits=8),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='production_config',
            field=models.JSONField(blank=True, default=dict, help_text='Disposition du suivi de production (widgets, ordre, portée)'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, help_text="Tél. de l'encadrant (affiché comme ETI sur la fiche d'émargement)", max_length=50),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Responsable de service'), ('technicien', 'Technicien / Chargé de projet'), ('comptable', 'Comptable'), ('rh', 'Ressources humaines')], default='technicien', max_length=20),
        ),
        migrations.CreateModel(
            name='Equipier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(blank=True, help_text="Identifiant RH stable (clé pour l'import futur)", max_length=50)),
                ('type_contrat', models.CharField(blank=True, default='CDDI - 26 heures', max_length=100)),
                ('heures_contrat_hebdo', models.DecimalField(decimal_places=2, default=Decimal('26.00'), help_text='Base contractuelle hebdomadaire (pour le calcul de récup)', max_digits=5)),
                ('date_debut_contrat', models.DateField(blank=True, null=True)),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('date_visite_medicale', models.DateField(blank=True, null=True)),
                ('recup_base_heures', models.DecimalField(decimal_places=2, default=0, help_text='Solde de récup de départ (saisi une fois)', max_digits=6)),
                ('recup_base_date', models.DateField(blank=True, help_text='Date du solde de récup de départ', null=True)),
                ('droit_conges_jours', models.DecimalField(decimal_places=2, default=0, help_text='Droit à congés (géré par la RH, non dérivé)', max_digits=6)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(blank=True, help_text='Équipe « maison » (rattachement par défaut)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipiers', to='core.equipe')),
            ],
            options={
                'verbose_name': 'Équipier',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('formation', 'Formation'), ('visite', 'Visite'), ('reunion', 'Réunion'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('creneau', models.CharField(blank=True, choices=[('matin', 'Matin'), ('aprem', 'Après-midi'), ('journee', 'Journée')], max_length=10)),
                ('decale_chantier', models.BooleanField(default=False, help_text="Repousse l'avancement du chantier (drapeau visuel, ajustement manuel)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.equipe')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['date_debut'],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='financeurs',
            field=models.ManyToManyField(blank=True, help_text="Financeurs affichés au pied de la fiche d'émargement", related_name='equipes', to='core.financeur'),
        ),
        migrations.CreateModel(
            name='TrancheDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Chantier complet', max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé (à facturer)'), ('facture', 'Facturé')], default='en_cours', help_text='termine = clôturé sur la timeline (à facturer) ; facture = signal levé', max_length=10)),
                ('termine_le', models.DateField(blank=True, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='core.devis')),
                ('termine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_clotures', to=settings.AUTH_USER_MODEL)),
                ('titres', models.ManyToManyField(blank=True, help_text='TITRE racines couverts (vide = tout le devis)', related_name='tranches', to='core.lignedevis')),
            ],
            options={
                'verbose_name': 'Tranche de devis',
                'ordering': ['devis', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_jours', models.DecimalField(blank=True, decimal_places=2, help_text='Longueur planifiée en jours ouvrés (défaut = jours facturables, ajustable aux poignées) — référence du décalage en cascade et du prévu', max_digits=6, null=True)),
                ('epingle', models.BooleanField(default=False, help_text='Date fixe : exclue du décalage automatique (chantier à échéance)')),
                ('vendredi_actif', models.BooleanField(default=False, help_text='Cette équipe travaille le vendredi sur cette période')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.equipe')),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.tranchedevis')),
            ],
            options={
                'verbose_name': 'Affectation',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ClotureMois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('cloture_le', models.DateTimeField(auto_now_add=True)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_faites', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures', to='core.equipe')),
            ],
            options={
                'verbose_name': 'Clôture mensuelle',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('equipe', 'annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creneau', models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi')], max_length=10)),
                ('heures', models.DecimalField(decimal_places=2, default=0, help_text="Heures travaillées sur ce demi-journée (au quart d'heure)", max_digits=4)),
                ('code', models.CharField(blank=True, choices=[('C', 'Congé'), ('R', 'Récupération'), ('M', 'Maladie'), ('AT', 'Accident du travail'), ('A', 'Absence'), ('AJ', 'Absence justifiée non rémunérée'), ('S', 'Suspension'), ('PMSMP', 'PMSMP'), ('DE', 'Démarches externes'), ('DI', 'Démarches internes'), ('F', 'Férié')], help_text="Code d'absence (vide = présent)", max_length=10)),
                ('observation', models.CharField(blank=True, max_length=300)),
                ('saisi_le', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.affectation')),
                ('equipier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.equipier')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'ordering': ['date', 'creneau'],
                'unique_together': {('equipier', 'date', 'creneau')},
            },
        ),
    ]
