# Generated by Django 6.0.5 on 2026-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_financeur_equipe_actif_equipe_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='module_planning',
            field=models.BooleanField(default=False, help_text='Ce service utilise le module Planning & Émargement (salariés en insertion)'),
        ),
    ]
