# Generated by Django 6.0.5 on 2026-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_service_module_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nb_equipiers',
            field=models.PositiveSmallIntegerField(default=4, help_text='Effectif théorique (base de calcul de la durée en planning)'),
        ),
    ]
