# Generated by Django 6.0.5 on 2026-06-06 19:43

import django.db.models.deletion
from django.db import migrations, models


def copy_equipe_to_equipes(apps, schema_editor):
    Evenement = apps.get_model('core', 'Evenement')
    for ev in Evenement.objects.filter(equipe__isnull=False):
        ev.equipes.set([ev.equipe_id])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_equipe_nb_equipiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='debut_creneau',
            field=models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi')], default='matin', max_length=5),
        ),
        migrations.AddField(
            model_name='affectation',
            name='fin_creneau',
            field=models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi')], default='aprem', max_length=5),
        ),
        migrations.AddField(
            model_name='evenement',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='evenements', to='core.equipe', verbose_name='Équipes concernées (vide = toutes)'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='travaille',
            field=models.BooleanField(default=False, help_text='True = jour normalement non-ouvré devient ouvré (vendredi de rattrapage…)'),
        ),
        migrations.RunPython(copy_equipe_to_equipes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='affectation',
            name='vendredi_actif',
            field=models.BooleanField(default=False, help_text='Déprécié — remplacé par les événements Evenement(travaille=True)'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='creneau',
            field=models.CharField(blank=True, choices=[('matin', 'Matin'), ('aprem', 'Après-midi'), ('journee', 'Journée')], default='journee', max_length=10),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='decale_chantier',
            field=models.BooleanField(default=False, help_text='Recalcule automatiquement les date_fin des chantiers couverts'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_legacy', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('formation', 'Formation'), ('visite', 'Visite'), ('reunion', 'Réunion'), ('journee_ferie', 'Jour férié / pont'), ('jour_sup', 'Jour supplémentaire'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
