# Generated by Django 6.0.5 on 2026-06-07 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_evenement_m2m_equipes_travaille_aff_creneau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets_crees', to=settings.AUTH_USER_MODEL)),
                ('equipe_hote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_recus', to='core.equipe')),
                ('equipier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='core.equipier')),
            ],
            options={
                'verbose_name': "Prêt d'équipier",
                'verbose_name_plural': "Prêts d'équipiers",
                'ordering': ['date_debut'],
                'unique_together': {('equipier', 'equipe_hote')},
            },
        ),
    ]
