# Generated by Django 6.0.5 on 2026-06-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_pret'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='creneau_debut',
            field=models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi')], default='matin', max_length=10),
        ),
        migrations.AddField(
            model_name='pret',
            name='creneau_fin',
            field=models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi')], default='aprem', max_length=10),
        ),
    ]
