# Generated by Django 6.0.5 on 2026-06-07 17:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_pret_creneaux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tranchedevis',
            options={'ordering': ['devis', 'ordre'], 'verbose_name': 'Tranche de devis', 'verbose_name_plural': 'Tranches de devis'},
        ),
        migrations.AddField(
            model_name='equipe',
            name='afficher_plie',
            field=models.BooleanField(default=False, help_text="Afficher le tampon PLIE en en-tête de la fiche d'émargement mensuelle"),
        ),
        migrations.AddField(
            model_name='equipe',
            name='heures_aprem_defaut',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Heures par défaut pour la demi-journée après-midi (émargement)', max_digits=4),
        ),
        migrations.AddField(
            model_name='equipe',
            name='heures_matin_defaut',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Heures par défaut pour la demi-journée matin (émargement)', max_digits=4),
        ),
        migrations.AddField(
            model_name='equipe',
            name='nom_programme',
            field=models.CharField(blank=True, help_text="Nom complet réglementaire du chantier d'insertion (ex. 'Atelier de Quartier Saint-Malo')", max_length=200),
        ),
        migrations.AlterField(
            model_name='presence',
            name='affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='core.affectation'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Responsable de service'), ('technicien', 'Technicien / Chargé de projet'), ('comptable', 'Comptable'), ('rh', 'Ressources humaines'), ('encadrant', 'Encadrant / ETI')], default='technicien', max_length=20),
        ),
        migrations.CreateModel(
            name='FicheNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('num_semaine', models.PositiveSmallIntegerField()),
                ('chantier_texte', models.CharField(blank=True, max_length=200)),
                ('observation_texte', models.TextField(blank=True)),
                ('equipier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_notes', to='core.equipier')),
            ],
            options={
                'verbose_name': 'Note de fiche',
                'verbose_name_plural': 'Notes de fiche',
                'unique_together': {('equipier', 'annee', 'mois', 'num_semaine')},
            },
        ),
    ]
