# Generated by Django 6.0.5 on 2026-06-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_fichenote_equipe_nullable_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='zone_financement_ext',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bibliothèqueaides',
            name='type_ligne',
            field=models.CharField(choices=[('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('FIN', 'Aide travaux CBB'), ('FINX', 'Financement organisme')], default='FIN', max_length=5),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('formation', 'Formation'), ('visite', 'Visite'), ('reunion', 'Réunion'), ('journee_ferie', 'Pont → Récup'), ('jour_sup', 'Jour supplémentaire'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='type_ligne',
            field=models.CharField(choices=[('F', 'Forfait'), ('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Aide travaux CBB'), ('FINX', 'Financement organisme'), ('TITRE', 'Titre')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='type_ligne',
            field=models.CharField(choices=[('F', 'Forfait'), ('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Aide travaux CBB'), ('FINX', 'Financement organisme'), ('TITRE', 'Titre')], max_length=5),
        ),
    ]
