# Generated by Django 6.0.5 on 2026-06-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_bibliothequeaides'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresassociation',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature + cachet de la directrice (PNG transparent recommandé)', null=True, upload_to='signature/'),
        ),
    ]
