# Generated by Django 6.0.5 on 2026-06-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_signature_directrice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='type_ligne',
            field=models.CharField(choices=[('F', 'Forfait'), ('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Aide travaux CBB'), ('FINX', 'Financement organisme'), ('TITRE', 'Titre'), ('PAGE', 'Saut de page')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='type_ligne',
            field=models.CharField(choices=[('F', 'Forfait'), ('FMO', "Forfait main d'œuvre"), ('FMAT', 'Forfait matériaux'), ('S', 'Ouvrage simple'), ('C', 'Ouvrage composite'), ('MO', "Main d'œuvre"), ('MAT', 'Matériau'), ('OUV', 'Sous-ouvrage'), ('FIN', 'Aide travaux CBB'), ('FINX', 'Financement organisme'), ('TITRE', 'Titre'), ('PAGE', 'Saut de page')], max_length=5),
        ),
    ]
