# Generated by Django 6.0.5 on 2026-06-20 23:35

from django.db import migrations, models

_PALETTE = [
    '#67123A', '#C2185B', '#C0392B', '#D35400', '#F7A600', '#827717',
    '#3B6D11', '#00AA8D', '#0097A7', '#185FA5', '#3949AB', '#5B3EA5',
    '#795548', '#546E7A',
]


def distribute_colors(apps, schema_editor):
    Profil = apps.get_model('core', 'ProfilUtilisateur')
    for i, p in enumerate(Profil.objects.order_by('pk')):
        p.couleur = _PALETTE[i % len(_PALETTE)]
        p.save(update_fields=['couleur'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ligndevis_type_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='couleur',
            field=models.CharField(choices=[('#67123A', '#67123A'), ('#C2185B', '#C2185B'), ('#C0392B', '#C0392B'), ('#D35400', '#D35400'), ('#F7A600', '#F7A600'), ('#827717', '#827717'), ('#3B6D11', '#3B6D11'), ('#00AA8D', '#00AA8D'), ('#0097A7', '#0097A7'), ('#185FA5', '#185FA5'), ('#3949AB', '#3949AB'), ('#5B3EA5', '#5B3EA5'), ('#795548', '#795548'), ('#546E7A', '#546E7A')], default='#546E7A', help_text='Couleur du liseré auteur dans les listes', max_length=7),
        ),
        migrations.RunPython(distribute_colors, migrations.RunPython.noop),
    ]
