# Generated by Django 6.0.5 on 2026-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_profil_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='planning_filtre_equipes',
            field=models.JSONField(blank=True, default=list, help_text="Ids d'équipes affichées dans le planning (filtre persistant ; vide = toutes)"),
        ),
    ]
