# Generated by Django 6.0.5 on 2026-06-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_profilutilisateur_planning_filtre_equipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='couleur',
            field=models.CharField(blank=True, choices=[('cha', 'Turquoise'), ('chb', 'Or'), ('chc', 'Prune'), ('chd', 'Bleu'), ('che', 'Violet'), ('chf', 'Vert'), ('chg', 'Terracotta'), ('chh', 'Ardoise')], help_text='Surcharge manuelle de la teinte du chantier (vide = attribution automatique)', max_length=3),
        ),
    ]
