# Generated by Django 6.0.5 on 2026-06-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_affectation_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='code_absence',
            field=models.CharField(blank=True, choices=[('C', 'Congé'), ('R', 'Récupération'), ('M', 'Maladie'), ('AT', 'Accident du travail'), ('A', 'Absence'), ('AJ', 'Absence justifiée non rémunérée'), ('S', 'Suspension'), ('PMSMP', 'PMSMP'), ('DE', 'Démarches externes'), ('DI', 'Démarches internes'), ('F', 'Férié')], help_text="Code d'absence posé automatiquement dans l'émargement des jours couverts", max_length=10),
        ),
    ]
