# Generated by Django 6.0.5 on 2026-06-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_evenement_code_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='archivee',
            field=models.BooleanField(default=False, help_text='Rangée temporaire archivée (date de fin dépassée) — masquée du planning'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='date_fin_temp',
            field=models.DateField(blank=True, help_text='Équipe temporaire : date de fin — archivée automatiquement après', null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='mo_forfait',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Renfort : montant MO forfaitaire (€), décorrélé de la durée', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='type_rangee',
            field=models.CharField(choices=[('permanente', 'Permanente'), ('temporaire', 'Temporaire'), ('renfort', 'Renfort'), ('prestataire', 'Prestataire')], default='permanente', help_text='Permanente (défaut) ou rangée ponctuelle (temporaire / renfort / prestataire)', max_length=12),
        ),
    ]
