# Generated by Django 6.0.5 on 2026-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_equipe_archivee_equipe_date_fin_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeur',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo téléversé (PNG/SVG). Affiché sur la feuille de présence ; à défaut, le nom du financeur est affiché dans un cadre.', null=True, upload_to='financeurs/'),
        ),
    ]
