# Generated by Django 6.0.5 on 2026-06-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_financeur_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipier',
            name='date_entree_cbb',
            field=models.DateField(blank=True, help_text="Date d'entrée chez les Compagnons Bâtisseurs (peut précéder le contrat courant)", null=True),
        ),
    ]
