# Generated by Django 6.0.5 on 2026-06-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_equipier_date_entree_cbb'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='importe_pdf',
            field=models.BooleanField(default=False, help_text="Devis importé depuis un PDF EBP : conserve sa référence d'origine (exclu de la renumérotation de la bascule)."),
        ),
    ]
